---
- name: Install Gnome (with Wayland support)
  command: "zypper --non-interactive install {{ gnome_packages }}"
  become: yes

- name: Enable GDM as the default display manager
  lineinfile:
    path: /etc/sysconfig/displaymanager
    regexp: '^DISPLAYMANAGER='
    line: 'DISPLAYMANAGER="gdm"'
    create: yes
  become: yes

- name: Ensure GDM uses Wayland
  blockinfile:
    path: /etc/gdm/custom.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      # Enable Wayland by default
      [daemon]
      WaylandEnable=true
    create: yes
  become: yes