---
- name: Configure zypper and upgrade system
  hosts: localhost
  roles:
    - configure-zypper
    - add-community-repos
    - system-upgrade
  tags:
    - system
    - opensuse-upgrade

- name: Configure some low-level settings
  hosts: localhost
  vars:
    blacklisted_modules: [ nouveau ]
    nvidia_packages: nvidia-drivers-G06 nvidia-gl-G06 nvidia-video-G06 nvidia-utils-G06
    nvidia_packages_32bit: nvidia-gl-G06-32bit nvidia-video-G06-32bit
  roles:
    - nvidia
    - blacklist-modules
  tags:
      - system
      - hardware
      - settings

- name: Configure the X server
  hosts: localhost
  vars:
    xorg_packages: xorg-x11-driver-input xorg-x11-driver-video xorg-x11-server xclip xinit
    window_manager_packages: bspwm sxhkd
  roles:
    - xorg-server
    - window-manager
  tags:
    - system
    - settings
