---
- name: Update zypper cache
  command: zypper refresh
  register: result
  until: result.rc == 0
  retries: 30
  delay: 10
  
- name: Upgrade the system
  command: zypper dup -y

- name: Reboot the server
  reboot:
      reboot_timeout: 300
  when: ansible_connection != 'local'
  
